language: julia
os:
  - linux
  - osx
julia:
  - 1.1
codecov: true

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg;
      Pkg.add(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.pin(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.add([PackageSpec(name="BinaryBuilder", rev="master"), PackageSpec(name="BinaryProvider")])'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
